audio:
  sample_rate: 16000

augmentations:
  noise_paths: "/path/to/noise/dataset"
  time_warp:
    min_rate: 0.8
    max_rate: 1.2
  pitch_shift:
    n_steps: 4
  reverb:
    strong: True

training:
  num_epochs: 2
  batch_size: 32
  learning_rate: 0.001
  checkpoint_interval: 100
  validation_interval: 200
  log_interval: 10

phase1:
  epochs: 1
  losses:
    reconstruction: True
    diversity: True
    cross_entropy: False
  weights:
    reconstruction: 2.0
    diversity: 1.0

phase2:
  losses:
    reconstruction: True
    diversity: True
    cross_entropy: True
  weights:
    reconstruction: 2.0
    diversity: 1.0
    cross_entropy: 0.005

cross_entropy:
  stabilization_threshold: 2e-1
  weight_increment_factor: 1.1
  max_weight: 10.0

diversity:
  synchronization_factor: 1.1
  threshold_number:
    50: 45
    100: 85
    200: 120
  max_weight: 10.0

datasets:
  train_tsv_path: "/path/to/train/tsv/file"
  val_tsv_path: "/path/to/val/tsv/file"
  test_tsv_path: "/path/to/test/tsv/file"

checkpoints:
  hubert: "/path/to/hubert"
  tokenizer: "/path/to/tokenizer"
  ulm: "/path/to/ulm"
